### ISSUE TITLE
Possible problem with Castle Resolver

### ISSUE THREAD

**Issue by alkampfergit** [ProximoSrl/Jarvis.DocumentStore#24]
Scenario: *we have a client that is polling feedcontroller, documentstore is stopped*. 
Then we start document store.

We start having this error on the documenstore.

```
System.InvalidOperationException: An error occurred when trying to create a controller of type 'FeedController'. Make sure that the controller has a parameterless public constructor. ---> System.ArgumentException: Type 'Jarvis.DocumentStore.Host.Controllers.FeedController' does not have a default constructor
   at System.Linq.Expressions.Expression.New(Type type)
   at System.Web.Http.Internal.TypeActivator.Create[TBase](Type instanceType)
   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.GetInstanceOrActivator(HttpRequestMessage request, Type controllerType, Func`1& activator)
   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType)
   --- End of inner exception stack trace ---
   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType)
   at System.Web.Http.Controllers.HttpControllerDescriptor.CreateController(HttpRequestMessage request)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
```

HEre is the declaration of the controller

![image](https://cloud.githubusercontent.com/assets/358545/20788759/54bc3774-b7b2-11e6-91a2-2672f550d611.png)

What is happening is probably: A first request arrives before the dependency is installed, OWIN is not capable of creating the controller, this break the resolution and it will never try to resolve again with castle.

Probably a solution could be: *Avoid starting OWIN before everything is installed correctly*

We need to investigate more this problem.

**Comment by alkampfergit** [comment]
This happens if someone calls for API with a tenant Id that is not configured in the system.
